# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build And Test

on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Move snapshots folders inside test folders
      run: |
        find ./ -type d -name "Snapshots" | while read snapshotFolder; do
          echo "Found Snapshots folder: $snapshotFolder"
          parent="$(dirname "$snapshotFolder")"
          echo "Parent directory: $parent"
          target="$parent/bin/Release/net10.0/Snapshots"
          echo "Target directory: $target"
          mkdir -p "$target"
          mv "$snapshotFolder"/* "$target"
          echo "Files inside directory: $target"
          ls -l "$target"
        done

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        retention-days: 1
        path: |
          **/bin/Release/net*/
          !**/ref/*

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: ./

    - name: Files inside Downloaded artifact
      run: |
        echo "build-output folder"
        ls -l

    - name: Test solution
      run: |
        find ./ -path "*/bin/*" -type f -name "*.Tests.dll" | while read testDll; do
          echo "Running tests in $testDll"
          chmod +x "$testDll"
          dotnet "$testDll" || exit $?
        done
