# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build And Deploy

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Move snapshots folders inside test folders
      run: |
        find ./ -type d -name "Snapshots" | while read snapshotFolder; do
          echo "Found Snapshots folder: $snapshotFolder"
          parent="$(dirname "$snapshotFolder")"
          echo "Parent directory: $parent"
          target="$parent/bin/Release/net10.0/Snapshots"
          echo "Target directory: $target"
          mkdir -p "$target"
          mv "$snapshotFolder"/* "$target"
          ls -l "$target"
        done
      
    - name: Test solution
      run: |
        find ./ -path "*/bin/*" -type f -name "*.Tests.dll" | while read testDll; do
          echo "Running tests in $testDll"
          chmod +x "$testDll"
          dotnet "$testDll" || exit $?
        done

    - name: Clean solution
      run: dotnet clean

    - name: Publish API
      run: dotnet publish ./BonefireCRM.API/BonefireCRM.API.csproj -c Release -o ./publish/api

    - name: Publish WebApp
      run: dotnet publish ./BonefireCRM.Web/BonefireCRM.Web.Server/BonefireCRM.Web.Server.csproj -c Release -o ./publish/webapp

    - name: Upload API build artifact
      uses: actions/upload-artifact@v4
      with:
        name: api
        retention-days: 1
        path: ./publish/api

    - name: Upload WebApp build artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        retention-days: 1
        path: ./publish/webapp
          
  Deploy:
    needs: Build
    runs-on: windows-latest
    steps:
    - name: Download API artifact
      uses: actions/download-artifact@v4
      with:
        name: api
        retention-days: 1
        path: ./publish/api

    - name: Download WebApp artifact
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ./publish/webapp
          
    - name: Deploy API to MonsterASP.NET via WebDeploy
      uses: rasmusbuchholdt/simply-web-deploy@2.1.0
      with:
        website-name: ${{ secrets.API_WEBSITE_NAME }}
        server-computer-name: ${{ secrets.API_SERVER_COMPUTER_NAME }}
        server-username: ${{ secrets.API_SERVER_USERNAME }}
        server-password: ${{ secrets.API_SERVER_PASSWORD }}
        source-path: '\publish\api\'

    - name: Deploy WebApp to MonsterASP.NET via WebDeploy
      uses: rasmusbuchholdt/simply-web-deploy@2.1.0
      with:
        website-name: ${{ secrets.WEB_WEBSITE_NAME }}
        server-computer-name: ${{ secrets.WEB_SERVER_COMPUTER_NAME }}
        server-username: ${{ secrets.WEB_SERVER_USERNAME }}
        server-password: ${{ secrets.WEB_SERVER_PASSWORD }}
        source-path: '\publish\webapp\'
